### ISSUE TITLE
Ability to right click a .tscn file in the file explorer and set/unset it as "scene_file" for debugging

### ISSUE THREAD

**Issue by ryerrappa** [godotengine/godot-vscode-plugin#180] opened 2020-05-18 15:51 UTC
The ability to set/unset a .tscn file as the "scene_file" for the debugger from the right click context menu in VS Code's file explorer.

This would be convenient when you want to spend time debugging a particular scene and changing that particular scene, rather than having to go into "launch.json" to set this.

Additionally maybe when setting/unsetting the "scene_file" configuration this way, maybe also make it toggle the "launch_scene" configuration

Thanks for the great work!

**Comment by ryerrappa** [comment] 2020-05-18 23:34
Don't know if this is allowed or the correct procedure, but I've begun to try implementing this on my own (complete beginner, sorry!) and I'm a little stuck.

I've managed to create a command which is exposed in the right click context menu only for .tscn files. Upon clicking the command, a configuration option should be written to which is then read. I've declared the configuration in "package.json" however I'm not able to read from, or write to, it. Reading from it only returns null. The weird thing is I'm able to read and write other configurations such as "godot-tools.editor_path" ([line 107 of package.json](https://github.com/godotengine/godot-vscode-plugin/blob/master/package.json#L98-L102)). 

There are only two configurations which can not be read or written to for me which are:
    1)my new configuration
    2)"godot-tool.check_status" ([line 112 of package.json](https://github.com/godotengine/godot-vscode-plugin/blob/master/package.json#L103-L107))

If this is inappropriate here or I'm just causing a hassle let me know. Thanks

**Comment by Razoric480** [comment] 2020-05-19 16:27
I'm not totally sure what godot-tool.check_status configuration is used for, as it's not used anywhere in the code.

I'm unable to reproduce your issue with a new, custom configuration (though godot-tool.check_status is currently entirely unused, from what I can tell.)

That said, your command should probably just append the relative path of the file to the `scene_file` property of an auto-configured configuration in the launch.json file. You'd simplify your life a lot instead of editing the user's global configuration.

**Comment by ryerrappa** [comment] 2020-05-19 19:32
> 
> 
> I'm unable to reproduce your issue with a new, custom configuration (though godot-tool.check_status is currently entirely unused, from what I can tell.) Unless you use get/set_configuration from utils but named your configuration "godot-tools" - the right prefix is "godot_tools"
> 
> That said, your command should probably just append the relative path of the file to the `scene_file` property of an auto-configured configuration in the launch.json file. You'd simplify your life a lot instead of editing the user's global configuration.

Yeah that was my fault. I used a - instead of an _ like you said. And yeah godot-tool.check_status was already there I guess made by a contributor. 

I have made a pull request for this (#182), if you would like to check it out. I think i have made a workspace configuration and not a global configuration but I'm not sure. Thank you for taking the time to reply!

**Comment by DaelonSuzuka** [comment] 2023-10-11 22:28
The associated PR for for this issue was merged so I'm considering this resolved.

**Closed by DaelonSuzuka** 2023-10-11 22:28 UTC
Labels: enhancement
