### ISSUE TITLE
Add the auto formatter disable setting

### ISSUE THREAD

**Issue by alagaG** [godotengine/godot-vscode-plugin#611] opened 2024-02-29 12:58 UTC
### Godot version

3.5.3.stable

### VS Code version

1.86.2

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 10

### Problem statement

I've wrote my whole project with the [official Godot style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) that differ from the current extension style guide. As example, the official recommendation is place 2 lines between methods, but the extension use just 1

### Proposed solution

Create a setting option disabling the auto formatter.

**Comment by DaelonSuzuka** [comment] 2024-02-29 19:51
This is a duplicate of #580, and as described there: Formatters in VSCode are only invoked when you request them. 

I suspect that you have the "formatOnSave" or "formatOnType" settings enabled. You can either disable that globally, or disable it for just GDScript by adding the following snippet to your global `settings.json` file.

```json
{
	"[gdscript]": {
		"editor.formatOnSave": false,
		"editor.formatOnType": false
	}
}
```

**Comment by alagaG** [comment] 2024-02-29 20:06
Thanks, it worked perfectly.

**Closed** 2024-02-29 20:06 UTC
Labels: enhancement
