### ISSUE TITLE
Crashing godot editor

### ISSUE THREAD

**Issue by willparsons** [godotengine/godot-vscode-plugin#295] opened 2021-08-29 21:30 UTC
If I try and edit any script in Godot it will crash indefinitely. 

I also get a message in VSCode about losing connection to the Godot editor, although I'm unsure if it loses connection first or just because the editor has crashed.

Uninstalling this plugin seems to remove the issue.

**Comment by Calinou** [comment] 2021-08-29 22:15
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by Calinou** 2021-08-29 22:15 UTC
