### ISSUE TITLE
Crashing on connecting to language server

### ISSUE THREAD

**Issue by TTSKarlsson** [godotengine/godot-vscode-plugin#294] opened 2021-08-28 11:13 UTC
VSCode 1.59.1
Godot v3.3.3.stable.official [b973f997f]

**What Happens and what I tried**

Godot crashing with this log when extension connects to language server
```log
Unable to read argv.json configuration file in C:\Users\tkarlsson\.vscode\argv.json, falling back to defaults (SyntaxError: Unexpected token } in JSON at position 205)
[main 2021-08-28T10:55:21.149Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-08-28T10:55:21.214Z] update#setState idle
[6944:0828/125521.231:ERROR:jump_list.cc(301)] Failed to append custom category 'Recent Folders' to Jump List due to system privacy settings.
[main 2021-08-28T10:55:21.261Z] SyntaxError: Unexpected token } in JSON at position 205
    at JSON.parse (<anonymous>)
    at Pe.afterWindowOpen (C:\code\resources\app\out\vs\code\electron-main\main.js:59:70214)
[main 2021-08-28T10:55:51.219Z] update#setState checking for updates
[main 2021-08-28T10:55:51.233Z] update#setState idle
```

File trying to get intellisense in:
![image](https://user-images.githubusercontent.com/9962943/131216075-2cffe8ca-6ac1-4d49-83f4-a1481285adbd.png)

Couldn't connect to language server
![image](https://user-images.githubusercontent.com/9962943/131215570-2030397a-dc6b-4f63-8ed9-37d143404c80.png)

Retry button does nothing because Godot has already crashed.

"Open Godot Editor" does (cmd.exe cli)
![image](https://user-images.githubusercontent.com/9962943/131215584-df80a3eb-a41f-4828-b7bd-bc0d97964676.png)

Godot editor is open beforehand and VSCode is opened from Godot.

VSCode settings
![image](https://user-images.githubusercontent.com/9962943/131215912-b1826ed1-4aa2-497c-90ea-fe9e40828bf6.png)
and also tried proper windows path
![image](https://user-images.githubusercontent.com/9962943/131215932-acf0e858-b6ce-4b41-ba51-298d29150325.png)
and "ws" as protocol a couple times, just to be sure

Godot editor settings:
Network->Debug
![image](https://user-images.githubusercontent.com/9962943/131215639-08cc6dc3-6a3f-40be-8be4-13976d142c54.png)

Network->Language Server
![image](https://user-images.githubusercontent.com/9962943/131215652-64ad5a01-4592-452e-95e9-23f15855505e.png)

**What I expect to happen**

I expect Godot not to crash and that I'll see intellisense for gdscript code.

**Comment by Calinou** [comment] 2021-08-28 14:41
Can you reproduce this in Godot 3.3.2? Can you reproduce this on the latest `3.x` branch compiled from source? If not, this is likely a duplicate of https://github.com/godotengine/godot/issues/51923.

**Comment by TTSKarlsson** [comment] 2021-08-28 15:45
It looks like the same issue, I'll get back as soon as I've been able to check.

**Comment by TTSKarlsson** [comment] 2021-08-28 17:44
@Calinou ,  I've now tested 3.3.2stable and the 3.3 branch. I had so much trouble compiling and when I finally succeeded I realized I compiled Godot 4....

Anyhooo... You are right, it is the same issue, works both on 3.3.2 and the unreleased 3.3 branch.

Thank you!

**Closed** 2021-08-28 21:00 UTC
Labels: bug, language server
