### ISSUE TITLE
Unique global class "..." already exists at path: ... (there's only one class named like this)

### ISSUE THREAD

**Issue by ErnestoBorio** [godotengine/godot-vscode-plugin#280] opened 2021-06-19 21:44 UTC
As you can see in the screenshot, the file where class `ZXprite` is defined is `res://src/ZXprite.gd`, so this error seems to be complaining about this class itself although it's not defined anywhere else.  
It's connected with the godot language server and I don't get this error in godot's built-in editor.

![Screen Shot 2021-06-19 at 18 39 19](https://user-images.githubusercontent.com/1771719/122656062-d3147980-d12d-11eb-9ae0-38d4f799dde2.png)

**Comment by Calinou** [comment] 2021-06-19 21:54
Do you still get this error if you restart both Godot and VS Code? Or just VS Code?

**Comment by ErnestoBorio** [comment] 2021-09-06 14:29
Sorry, don't remember how I fixed it, but I did. Whenever I resume this project I'll take a look and close this issue.
Thanks!

**Comment by bryab** [comment] 2021-12-21 17:07
I had this issue and it was resolved by restarting Godot Editor (not restarting VS Code)

**Comment by nickgirga** [comment] 2022-05-24 09:55
I've found what was causing this issue for me and can reproduce and solve the issue. The reason it was happening for me was because I was using a symlink to a directory on an external drive to access my project in VSCode (`~/Projects` -> `/run/media/nick/LinuxStorage/Projects`). I noticed when I opened the file directly using the full path, it didn't show the error. So, I closed the folder and reopened it in VSCode using the full path on the external drive and the errors went away even in the project explorer and the problems panel. To see if that really was the issue, I closed the folder and reopened VSCode using the symlink, and sure enough, it gave me the error again. Closed and reopened VSCode with the full path and the error went away completely again. For me, I'm certain it was the fact that I was using symlinks/shortcuts (and possibly the external drive played a role).

**Comment by Muha0644** [comment] 2022-08-02 12:35
I am having the same issue, i am not using any symlinks. My project is in my home directory and vscode. The error is only present in VSC and not in Godot. Every class I define is flagged as a duplicate of itself.

**Comment by raietracer** [comment] 2022-08-16 21:55
I'm trying to figure out a workaround for this issue.  I'm having it as well.  It occurs for me in a project that is a repository clone.  I've tried opening all of the given suggestions and checked for symlinks but to my knowledge there isn't one.

**Comment by DaelonSuzuka** [comment] 2022-08-17 03:45
As far as I can tell, it just does this sometimes. I'm fairly confident that the error is coming from the language server and can't really be fixed in this extension.

I could probably add an option to suppress the error locally if anybody is interested in a band-aid fix.

**Comment by DaelonSuzuka** [comment] 2024-02-28 07:23
This isn't an extension issue, but it happens much less frequently(maybe not at all?) for me using Godot 3.5+ and Godot 4.2+.

**Closed by DaelonSuzuka** 2024-02-28 07:23 UTC
Labels: bug, language server
