### ISSUE TITLE
Can't see scene tree (remote) from the godot when start debugger

### ISSUE THREAD

**Issue by marko995** [godotengine/godot-vscode-plugin#567] opened 2024-01-10 23:48 UTC
### Godot version

4.2.1

### VS Code version

1.85.1

### Godot Tools VS Code extension version

master

### System information

Fedora 38

### Issue description

Hi, I am not sure if is it bug or something else, but when I start debugger from vscode, I can't see remote tab in the scene tree, like when I start debugger from the godot itself. Is it possible to fix that?

![Screenshot from 2024-01-11 00-47-25](https://github.com/godotengine/godot-vscode-plugin/assets/26909234/c84749c1-5fdb-401f-a906-76a0a7b69f45)

### Steps to reproduce

Hit f5 from vscode.

**Comment by DaelonSuzuka** [comment] 2024-01-11 05:13
Sounds like a duplicate of #565.

**Comment by DaelonSuzuka** [comment] 2024-02-28 04:35
> Hi, I am not sure if is it bug or something else, but when I start debugger from vscode, I can't see remote tab in the scene tree, like when I start debugger from the godot itself. Is it possible to fix that?

Unfortunately, I haven't found a way to start a game instance in debug mode and have both debuggers connected to it. 

You'll have to pick between debugging your game with the Godot Editor or with VSCode.

**Closed by DaelonSuzuka** 2024-02-28 04:35 UTC
Labels: bug
