### ISSUE TITLE
Running game from VSCode and remote nodes

### ISSUE THREAD

**Issue by rohanrhu** [godotengine/godot-vscode-plugin#216] opened 2020-07-15 02:57 UTC
If we run the game from VSCode, we are not able to see remote nodes.

**Comment by Razoric480** [comment] 2020-07-16 15:32
@rohanrhu Can you clarify what you mean? When debugging the game there is an active scene tree that mirrors what the Remote panel in the editor does. It does not automatically refresh but there is a refresh button.

Unless you mean Remote nodes as something else?
![image](https://user-images.githubusercontent.com/2823241/87690890-fc779900-c757-11ea-8b68-0178e24d5e77.png)

**Comment by rohanrhu** [comment] 2020-07-16 15:40
VSCode's scene tree is empty when i run the game. (Also Godot's is empty too.)

**Comment by ndarilek** [comment] 2020-07-16 17:56
Seeing the same behavior. Since I can't even see a remote scene tree in Godot itself, I suspect a Godot issue. I do see "Failed to connect to port 6007" or something similar when launching a game from within the editor. Something is definitely listening on 6007. I also just tried downgrading to Godot 3.2.1 with no change. This definitely worked at one point but doesn't anymore.

Is there a way to get a debugging session from the console, since the GUI isn't working?

Or is this being tracked in Godot? A quick skim of open issues didn't reveal anything.

Thanks.

**Comment by Razoric480** [comment] 2020-07-16 18:07
@rohanrhu @ndarilek Can you post your launch.json file?

**Comment by ndarilek** [comment] 2020-07-16 18:11
{
     // Use IntelliSense to learn about possible attributes.
     // Hover to view descriptions of existing attributes.
     // For more information, visit: 
https://go.microsoft.com/fwlink/?linkid=830387
     "version": "0.2.0",
     "configurations": [
         {
             "name": "Godot",
             "type": "godot",
             "request": "launch",
             "project": "${workspaceFolder}",
             "port": 6007,
             "address": "127.0.0.1",
             "launch_game_instance": true,
             "launch_scene": false
         }
     ]
}

**Comment by Razoric480** [comment] 2020-07-16 18:18
When you say that there's no Remote tree in Godot, do you mean that when you debug Godot without the use of VSCode, even Godot doesn't show the remote scene tree link?

**Comment by ndarilek** [comment] 2020-07-16 18:39
Yes, exactly. But I've just made another interesting discovery.


1. Open a Godot project in VSCode, but without opening the Godot editor. 
Not sure how relevant not opening the editor is--I just wanted a simple 
set of steps.

2. Ignore the "Can't connect to language server" warning.

3. Launch your game with F5.

4. Switch to a console and attempt connecting to localhost:6007. Notice 
it connects.

5. Quit the game using `get_tree().quit()`.

6. Despite the game exiting, port 6007 is open and remains open until 
VSCode itself is quit. So it doesn't seem like the game is on 6007.


I still don't see a remote tree in VSCode's debugger, but now that I've 
discovered that VSCode itself seems to keep the port open after the game 
is quit, I'm wondering if that's the cause? I.e. something in VSCode 
seems to be opening up port 6007, not Godot, and the debugger isn't 
connecting to the game but instead to whatever is opening this port. 
Quitting VSCode kills whatever is listening on 6007, and I can once 
again browse remote trees from the Godot editor. But as soon as VSCode 
hijacks 6007, nothing works. I've also confirmed that there are no Godot 
processes running when I've exit the game from VSCode.

**Comment by Razoric480** [comment] 2020-07-16 18:52
Do breakpoints work?

If not, can you try going into the launch.json and change the port from 6007 to something else? Like 32753 or something else totally arbitrary that is unlikely to be in use, see if that works.

**Comment by ndarilek** [comment] 2020-07-16 18:58
Interesting, breakpoints do seem to work. Changing the port does 
nothing, other than making VSCode hold the newly-specified port open 
(nothing opens 6007.)


Is it possible to get a log of communication between the extension and 
the debugger?

**Comment by jsbeckr** [comment] 2020-08-11 15:32
Duplicate of #222 ?

**Comment by Razoric480** [comment] 2020-08-11 15:46
Sorry, @ndarilek , life got in the way. Can you try the custom VSIX I have in a comment [here](https://github.com/godotengine/godot-vscode-plugin/issues/222#issuecomment-671702907)?

**Comment by linkpy** [comment] 2020-10-28 13:56
Duplicate of #222.
Can't reproduce the issue on my hand.

**Comment by Calinou** [comment] 2020-10-28 14:15
Closing per @linkpy's comment.

**Closed by Calinou** 2020-10-28 14:15 UTC
Labels: bug
