### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Soaku** [godotengine/godot-vscode-plugin#111] opened 2019-08-29 08:32 UTC
When Godot starts and VSCode shortly after, the client connects fine, but it seems to have issues in some cases. For example, when the editor crashes and is then restarted, the client will be stuck at "initializing" or "connecting". Even restarting VSCode doesn't fix the issue.

I'll attempt to collect more data on when exactly does this happen, but this is all I know for now.

By the way, would be nice if inspections were disabled while the server isn't connected. Otherwise errors highlightings get stuck in the editor even when they are no longer valid.

E: Godot just crashed. Restarting VSCode did help though.

**Comment by okapii** [comment] 2019-12-03 15:55
I too encounter connection issues. In my case "Initializing" never changes in the bottom right corner even when the connection seems to be established correctly and the extension is working as expected. After some time intellisense stops working which can be fixed by restarting Godot and manually reestablishing the connection. However at that point it isn't possible anymore to simply restart Godot. Instead one has to kill off the application with the task manager. This happens 3-4 times per hour which probably indicates that the issues might not be caused by the application but by Godot.

Sadly I haven't figured out a way to reliably reproduce this yet. The only thing I noticed so far is the fact that I can shorten the time until the issue appears by triggering many actions like showing the tooltips using <cmd>-<k> <cmd>-<i> or <ctrl>-<shift>.
I will let you know if I figure out a more precise way to reproduce the issue.

I am working on a Mac with the most recent MacOS version.

**Comment by okapii** [comment] 2019-12-05 15:30
The problem seems to have been resolved for me in 3.2b3.

**Comment by Geequlim** [comment] 2019-12-07 04:35
> In my case the "Initializing"-text never changes in the bottom right corner even when the connection seems to be established correctly and the extension is working as expected. 

This seems to be an issue of VSCode I have reported to the upstream repo #86508

**Comment by Geequlim** [comment] 2020-01-16 16:10
Fixed by
https://github.com/godotengine/godot/pull/35074

**Closed by Geequlim** 2020-01-16 16:10 UTC
Labels: bug
