### ISSUE TITLE
Add GDScript formatter

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#395] opened 2022-07-22 06:09 UTC
### Godot version

N/A

### VS Code version

N/A

### Godot Tools VS Code extension version

N/A

### System information

N/A

### Problem statement

Sometimes you just write codes without thinking about the formatting and when you know it, the poor formatting became too much to manually go through and fix.

This is more of a quality of life stuff but eh.

### Proposed solution

Implementing a formatter that follows the [GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html).

**Comment by Calinou** [comment] 2022-07-22 17:24
Duplicate of https://github.com/godotengine/godot-proposals/issues/3630. Once that proposal is implemented, we can add a way for this extension to call into the language server to request formatting for the current file.

**Closed by Calinou** 2022-07-22 17:24 UTC
Labels: enhancement
