### ISSUE TITLE
class_name does not update language server

### ISSUE THREAD

**Issue by cameron-hu-ginkgo** [godotengine/godot-vscode-plugin#259] opened 2021-02-18 10:25 UTC
Example:

Create script `Item.gd`:
```
extends Node
class_name Item
```

Create script `Weapon.gd`:
```
extends Item
```

Run Godot and get

Error:
Unknown class: "Item"

If I do this in the Godot editor it works perfectly

**Comment by Calinou** [comment] 2021-02-18 14:56
Duplicate of https://github.com/godotengine/godot/issues/42786 (this is a language *server* bug).

**Closed by Calinou** 2021-02-18 14:56 UTC
Labels: bug
