### ISSUE TITLE
Language Server is closing unexpectly

### ISSUE THREAD

**Issue by blacknoize404** [godotengine/godot-vscode-plugin#298] opened 2021-09-07 17:30 UTC
The language server connects properly to VS Code but just when I make a minimal change in the code, Godot, and consequently the language server closes making it impossible to work from VS Code.

I have followed the configuration steps ->

Checked "Use External Editor"

I have added the address of my VS Code which resides in its default location in "AppData / Programs".

And I have written in "Exec Flags" -> "{project} --goto {file}: {line}: {col}"

Am I skipping any steps to properly link VS Code with Godot?

I am using VS Code 1.59.1 and Godot 3.3.3.stable.official.b973f997f on Windows 10 21h1.

**Comment by Calinou** [comment] 2021-09-07 18:27
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by Calinou** 2021-09-07 18:27 UTC
