### ISSUE TITLE
Newline inserting too many tabs/spaces

### ISSUE THREAD

**Issue by bg641** [godotengine/godot-vscode-plugin#221] opened 2020-07-19 00:26 UTC
Steps to reproduce:
1. Following code:
```
func testfunc():
    for x in 5:
        for y in 10:
            for z in 20:
                pass
    
    var tmp = 5
    
    var tmp2 = 5
```

2. Move cursor to the line between `var tmp = 5` and `var tmp2 = 5`
3. Press tab

The cursor will jump to the same indentation level as `pass`, rather than just inserting one tab-length

**Comment by Calinou** [comment] 2020-07-19 10:40
Related to #220.

**Comment by linkpy** [comment] 2020-10-28 13:51
Duplicate of #219, both have the same underlying issue (see the other issue for more info).

**Comment by Calinou** [comment] 2020-10-28 14:14
Closing per @linkpy's comment.

**Closed by Calinou** 2020-10-28 14:14 UTC
Labels: bug
