### ISSUE TITLE
Breakpoints set in VS Code are never hit.

### ISSUE THREAD

**Issue by ldmfield** [godotengine/godot-vscode-plugin#223] opened 2020-08-18 20:34 UTC
I've set breakpoints in VS code but nothing ever gets hit.

`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [        
        {
            "name": "Godot",
            "type": "godot",
            "request": "launch",
            "project": "${workspaceFolder}",
            "port": 6007,
            "address": "localhost",
            "launch_game_instance": true,
            "launch_scene": false
        },
    ]
}
`

**Comment by Calinou** [comment] 2020-08-18 22:19
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/168.

**Closed by Calinou** 2020-08-18 22:19 UTC
