### ISSUE TITLE
Node path suggestion snippet print duplicate double quote and bracket

### ISSUE THREAD

**Issue by vanviethieuanh** [godotengine/godot-vscode-plugin#301] opened 2021-10-02 12:58 UTC
https://user-images.githubusercontent.com/29355962/135716957-cdc74a70-ddad-4e79-988c-eba999f74e2c.mp4

The problem happend when I use get_node or path to a file then the snippet with print out it with the `"` I wrote before (clearly if I don't write that `"`, it will never suggest me the path). And far more strange when it print with a `(`, is it a bug or anyway to fix it ?
Thank you!

I'm using 
```
Godot v 3.3.2 and 
VSCode Version: 1.60.2
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-7614-generic
```

**Comment by Calinou** [comment] 2021-10-02 14:57
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/142.

**Closed by Calinou** 2021-10-02 14:57 UTC
