### ISSUE TITLE
Double quotes with action string autocomplete

### ISSUE THREAD

**Issue by LeifintheWind** [godotengine/godot-vscode-plugin#427] opened 2022-10-03 20:20 UTC
### Godot version

3.5.1

### VS Code version

1.71.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

When using autocomplete for a string inside of a function, the autocomplete includes the quotes for the string but does not show up until quotes have already been typed. This leads the autocomplete adding an extra set of quotes to the string.
![image](https://user-images.githubusercontent.com/114954877/193672919-66260085-c3af-4978-b3ea-246369607eca.png)
![image](https://user-images.githubusercontent.com/114954877/193672970-3836ee86-5ac2-4582-be00-0342d02817aa.png)

### Steps to reproduce

Type a function that requires a string input, then type the quotes and use autocomplete to fill in the string.

**Comment by Calinou** [comment] 2022-10-03 20:47
Duplicate of https://github.com/godotengine/godot/issues/48436.

**Closed by Calinou** 2022-10-03 20:47 UTC
Labels: bug
