### ISSUE TITLE
Wrong completion for input name(ui_left, ui_right,...)

### ISSUE THREAD

**Issue by tienlocnguyen** [godotengine/godot-vscode-plugin#151] opened 2020-02-26 12:56 UTC
When I use `Input.get_action_strength`, auto complete suggest correct input option: ui_left, ui_right....
![image](https://user-images.githubusercontent.com/6823008/75346805-106a4d80-58d2-11ea-8445-ed63d63b897f.png)

But when choose one, the completion is wrong:
```
Input.get_action_strength(""ui_right"("
```
May be there's conflict with built-in vscode autocomplete function

PS: Here's result when auto complete `_physics_process`:
```
func _physics_process(delta: float) -> void:(
```
There's same redundant `(` in result
I'm not sure it's same issue or not

**Comment by Calinou** [comment] 2020-02-26 14:17
Duplicate of #142.

**Closed by Calinou** 2020-02-26 14:17 UTC
Labels: bug
