### ISSUE TITLE
Add Lines Before "extends Node" Result in Outline Not Working

### ISSUE THREAD

**Issue by hayahane** [godotengine/godot-vscode-plugin#658] opened 2024-05-18 02:22 UTC
### Godot version

4.3dev6

### VS Code version

1.89.1

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 11

### Issue description

The outline does not work properly when "extends Node" not in the first Line.
I've found several situation：
- class_name in the first line, and extends in the second:
**[work properly]**
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/b3a19a17-efaa-4a58-ba13-0dab045d1ad9)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/883dd341-8547-4c2e-9b95-707785def514)
**[not working]**
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/33f4e04e-5a78-4abf-b388-8a32f92473a4)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/1d3a351a-2339-4430-9fd7-f42f009a3d76)

- use icon notation:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/5a391fc0-2cb8-48f0-bbb3-7d42b7652b75)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/dfefe83c-c2a3-4c2b-a416-fd7885b612cd)

- write comments when not using class_name:
**[comments without class_name]**
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/a0d69937-e2f5-442e-8829-bc1925d5ccd0)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/505eb10b-a3fa-48a4-8dfe-c0b9ce994ae7)
**[comments with class_name]**
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/fca53cae-42a1-42d0-858a-417ddd7201af)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/39263675/a8eda129-721c-4100-9d4c-74626e1109aa)

### Steps to reproduce

Simply write a piece of code.
The situations I found are above.

**Comment by limbonaut** [comment] 2024-08-26 10:41
I can confirm this issue with some of the LimboAI scripts, such as:
https://github.com/limbonaut/limboai/blob/master/demo/demo/agents/scripts/agent_base.gd

**Comment by DaelonSuzuka** [comment] 2024-09-08 03:47
Yeah, this is a bug in the Language Server, and the issue needs to be raised in the https://github.com/godotengine/godot repo.

**Comment by HolonProduction** [comment] 2024-10-14 08:53
> Yeah, this is a bug in the Language Server, and the issue needs to be raised in the https://github.com/godotengine/godot repo.

Did you look into what the Server is actually doing wrong? Looking at the traces from godotengine/godot#98164 the responses seem correct at a first glance.

**Comment by DaelonSuzuka** [comment] 2024-10-14 14:50
@HolonProduction I will have to look into this further. This extension doesn't control the outline, it forwards those messages directly to VSCode, so if only works sometimes then (in theory) there is a bug in either VSCode or the Language Server.

**Comment by HolonProduction** [comment] 2024-11-15 18:48
@DaelonSuzuka it is in fact an (not very obvious) issue with the LSP, see https://github.com/godotengine/godot/pull/99295. I guess it would be fine to close this issue again.

**Comment by DaelonSuzuka** [comment] 2024-11-15 18:50
That makes a lot of sense, thanks for investigating!

**Comment by HolonProduction** [comment] 2024-11-28 11:44
I'll close the issue since the upstream issue has been closed as well.

**Closed by HolonProduction** 2024-11-28 11:44 UTC
Labels: bug, needs testing, language server
