### ISSUE TITLE
Add setting to disable the "couldn't connect" popup warning message

### ISSUE THREAD

**Issue by AlfishSoftware** [godotengine/godot-vscode-plugin#463] opened 2023-04-07 03:34 UTC
### Godot version

4.0.1.stable

### VS Code version

1.77.1

### Godot Tools VS Code extension version

1.3.1

### System information

Ubuntu

### Problem statement

Often, when working with Flathub version of Godot, or just when one wants to inspect the project without necessarily opening Godot, the popup warning that the plugin couldn't connect to Godot appearing every time is annoying.

Sometimes you just want syntax highlighting and don't care about the rest. Plus, you can already manually show the popup again by clicking the "Disconnected" button in the status bar anyway. Currently the only way to avoid this warning is by setting `godot_tools.reconnect_cooldown` to a giant number like `999999999`.

### Proposed solution

Please add a setting to disable the popup warning. Then, when it stops trying to reconnect, it should just act as if you clicked Ignore, without showing the popup. If you want to see it you can always just click Disconnected. E.g.:
```jsonc
"godot_tools.warn_unable_to_connect": false, // default true
```

**Comment by DaelonSuzuka** [comment] 2023-04-07 15:30
This is actually something that's been discussed here before and I think it's a good idea. I can probably implement this after I get the debugger fixes done.

**Comment by Calinou** [comment] 2023-04-07 16:15
- Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/434.

**Closed by Calinou** 2023-04-07 16:15 UTC
Labels: enhancement
