### ISSUE TITLE
Incorrect quoting when autocompleting NodePath suggestions

### ISSUE THREAD

**Issue by naim** [godotengine/godot-vscode-plugin#394] opened 2022-07-20 21:41 UTC
### Godot version

3.4.4.stable

### VS Code version

1.69.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10 Pro

### Issue description

When typing `get_node("Poly|")` (pipe represents cursor; the trailing `")` were inserted automatically) autocomplete options popped up for my child nodes -- in this case `Polygon2D`. When I accepted the autocomplete suggestion, what was produced was this: `get_node(""Polygon2D"(")`. The autocomplete suggestion shows quotes around it (see screenshots). Interestingly, if there's a syntax error in the file and you try to do it again, it doesn't show the same autocomplete suggestions (see third screenshot).

Additionally, node path suggestions don't always properly reflect the tree -- if I have two nodes both with the same script attached but with different child nodes, only the nodes in the last instance are reflected.

![image](https://user-images.githubusercontent.com/92351/180085578-7a49cc7c-cd77-4b3a-9159-c8c13392dcbb.png)

After accepting:
![image](https://user-images.githubusercontent.com/92351/180085690-9a5cb019-39ba-4d4d-b063-cbcdcdb1efe8.png)

If there's a syntax error in the file:
![image](https://user-images.githubusercontent.com/92351/180086120-aae75dfa-8be7-430c-b5d1-303d0631f611.png)

### Steps to reproduce

- Create the following node tree:
![image](https://user-images.githubusercontent.com/92351/180086943-54c87c42-cae2-4c35-ad05-7c36a58d2c20.png)

- Attach gdscript file to "Obstacle 1"
- Type `get_node("Pol`
- Autocomplete to one of the quoted suggestions

**Comment by Calinou** [comment] 2022-07-20 22:03
Duplicate of https://github.com/godotengine/godot/issues/48436.

**Closed by Calinou** 2022-07-20 22:03 UTC
Labels: bug
