### ISSUE TITLE
Add support for documentation in other languages

### ISSUE THREAD

**Issue by WangPengJu** [godotengine/godot-vscode-plugin#695] opened 2024-08-16 15:11 UTC
### Godot version

4.3

### VS Code version

1.92.2

### Godot Tools VS Code extension version

2.1.0

### System information

Windows 10

### Problem statement

just like a built-in editor, open documents in whichever language you choose

### Proposed solution

support other languages

**Comment by DaelonSuzuka** [comment] 2024-08-17 01:40
Duplicate of #617.

This isn't possible because the Godot Engine/Editor doesn't support it.

**Closed by DaelonSuzuka** 2024-08-17 01:40 UTC
Labels: enhancement
