### ISSUE TITLE
Formatter breaks up xor assignment operator

### ISSUE THREAD

**Issue by WesleyClements** [godotengine/godot-vscode-plugin#657] opened 2024-05-07 20:08 UTC
### Godot version

4.2.2

### VS Code version

1.89.0

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 11

### Issue description

The formatter will add a space in between the `^` and `=` in the xor assignment operator.
This:
```gdscript
var num = 4
num ^= 20
```
turns into this:
```gdscript
var num = 4
num^ = 20
```
This is invalid gdscript and so breaks compilation.

### Steps to reproduce

Use the xor assignment operator anywhere and then format the document.

**Comment by tarwich** [comment] 2024-06-21 11:43
Duplicate of #653 #601 #602 #609

Resolved in #605

**Comment by DaelonSuzuka** [comment] 2024-11-03 16:21
I believe the fix for this was already published, but I just added some extra tests to cover this.

**Closed by DaelonSuzuka** 2024-11-03 16:21 UTC
Labels: bug
