### ISSUE TITLE
some keywords aren't highlighted

### ISSUE THREAD

**Issue by balintbarna** [godotengine/godot-vscode-plugin#277] opened 2021-06-15 11:11 UTC
"and" "not" and "or" aren't highlighted as special words as they are in e.g. Python
![image](https://user-images.githubusercontent.com/13272850/122042953-1774e200-cddb-11eb-8727-72d151d48fc6.png)

**Comment by Calinou** [comment] 2021-06-15 16:45
`and`/`or` are defined in the syntax highlighting file: https://github.com/godotengine/godot-vscode-plugin/blob/master/syntaxes/GDScript.tmLanguage.json#L89-L92

I suppose the issue is that no color is assigned to them (it must be provided by the theme).

**Comment by balintmaci** [comment] 2021-06-16 06:31
I'm using the dark+ theme
Python for comparison:
![image](https://user-images.githubusercontent.com/13272850/122168966-2b712000-ce7d-11eb-9055-3911d9ad7740.png)

**Comment by dhAlcojor** [comment] 2021-07-30 09:56
@balintmaci There is a [GDScript Theme](https://marketplace.visualstudio.com/items?itemName=JamesSauer.gdscript-theme&utm_source=VSCode.pro&utm_campaign=AhmadAwais) that highlights these correctly:
![image](https://user-images.githubusercontent.com/567687/127635947-a0911fc5-cf2b-4ae0-ac02-ad8303137075.png)
![image](https://user-images.githubusercontent.com/567687/127636010-f759814c-5012-4dfb-befc-fe8be14c9f95.png)

It gives GDScript code the same (more or less) colors as in Godot editor, which I love.

**Comment by was-games** [comment] 2021-11-03 13:26
With the Dark+ theme it looks like this for me:
![image](https://user-images.githubusercontent.com/89310925/140068208-2465cf1f-8443-4fba-943c-ee4fc5c12331.png)

**Comment by DaelonSuzuka** [comment] 2023-10-12 02:48
This has definitely been fixed.

**Closed by DaelonSuzuka** 2023-10-12 02:48 UTC
Labels: bug
