### ISSUE TITLE
No symbols found in @tool scripts in outline in Godot 4.3

### ISSUE THREAD

**Issue by Tattomoosa** [godotengine/godot-vscode-plugin#725] opened 2024-09-24 18:30 UTC
### Godot version

4.3.stable

### VS Code version

1.93.1

### Godot Tools VS Code extension version

2.2.0

### System information

MacOS 14.6.1

### Issue description

Symbols aren't showing up correctly for any scripts with the @tool annotation in 4.3 stable (or 4.4.0-dev.1). Works correctly in 4.2.2. Not sure if this is an issue in the plugin or the Godot LSP itself but figured someone here could help me determine that.

Symbols do work fine in 4.3 stable in Godot's internal editor, but as I understand it the internal editor doesn't use the LSP so that might not mean anything.

### Steps to reproduce

Create a new Godot project
Create a script, eg:
```
extends Node

func some_function():
	print("hi")
```
Looks ok!
<img width="795" alt="Screenshot 2024-09-24 at 10 56 08" src="https://github.com/user-attachments/assets/37be3949-d76b-4849-9042-a05ceeffce23">

Add tool annotation:
```
@tool
extends Node

func some_function():
	print("hi")
```
No more symbols :(
<img width="708" alt="Screenshot 2024-09-24 at 10 56 44" src="https://github.com/user-attachments/assets/651c55f4-db82-434f-80fa-c0ecd727a008">

**Comment by DaelonSuzuka** [comment] 2024-09-24 20:11
Duplicate of #658

**Closed by DaelonSuzuka** 2024-09-24 20:11 UTC
Labels: bug

**Comment by DaelonSuzuka** [comment] 2024-09-24 21:25
Just to summarize: the issue is not the `@tool` annotation, the issue is when _anything_ comes before `extends <blah>`. This is a bug in the Language Server, not this extension, and you should open an issue on the Godot Engine.
