### ISSUE TITLE
Connecting a signal doesn't create a function when using Code.

### ISSUE THREAD

**Issue by IRONIC3D** [godotengine/godot-vscode-plugin#248] opened 2020-11-03 04:18 UTC
Using GDScript with VSCode with Godot 3.2.3

Trying to connect a signal to a script while using Code will not create the function. Instead the cursor jumps to beginning of the code. Reloading the script file or reloading the project does not resolve the issue. The code is never created. Works only when disabling the external editor.

**Comment by Calinou** [comment] 2020-11-03 13:10
Duplicate of https://github.com/godotengine/godot/issues/41283. (This is an issue in the Godot editor, not the VS Code extension.)

**Closed by Calinou** 2020-11-03 13:10 UTC

**Comment by IRONIC3D** [comment] 2020-11-03 22:21
Thanks Hugo.
