### ISSUE TITLE
Adding twice " when completing a path/anything in ""

### ISSUE THREAD

**Issue by hero2002** [godotengine/godot-vscode-plugin#414] opened 2022-08-29 19:05 UTC
### Godot version

3.5.stable

### VS Code version

1.69

### Godot Tools VS Code extension version

1.1

### System information

Win 10

### Issue description

the autocomplete is adding twice the " as needed
![image](https://user-images.githubusercontent.com/20283475/187278393-f39e221b-490e-4ca3-a881-185aef261381.png)

### Steps to reproduce

1- type ``Input.is_action_pressed():``
2- add "" inside the closures 
3- choose an option from the list
4- it will become ``Input.is_action_pressed(""ui_accept""):``

**Comment by Calinou** [comment] 2022-08-30 14:41
Duplicate of https://github.com/godotengine/godot/issues/48436. Please search in both open and closed issues before opening an issue :slightly_smiling_face:

**Closed by Calinou** 2022-08-30 14:41 UTC
Labels: bug
