### ISSUE TITLE
Bug. Outline View doesn't work if file starts with a comment and the class_name not used.

### ISSUE THREAD

**Issue by BrianOSH** [godotengine/godot-vscode-plugin#759] opened 2024-11-25 19:11 UTC
### Godot version

4.3

### VS Code version

1.95.3

### Godot Tools VS Code extension version

2.7.0

### System information

Linux Mint 5.15.0-126-generic

### Issue description

File must start with a comment

```
##----------------------------
## Outline View Doesn't Works
##----------------------------
extends Button

##----------------------------
## Outline View Works
##----------------------------
class_name Name extends Button
```

- Extension version: 2,7,0
- VSCode version: v1.95.3
- OS version: Linux Mint 5.15.0-126-generic

### Steps to reproduce

-

**Comment by DaelonSuzuka** [comment] 2024-11-25 20:30
Duplicate of #658.

**Closed by DaelonSuzuka** 2024-11-25 20:30 UTC
Labels: bug
