### ISSUE TITLE
VSCode does not recognize class names until closing and reopening Godot

### ISSUE THREAD

**Issue by MarcusDobler** [godotengine/godot-vscode-plugin#238] opened 2020-10-14 12:22 UTC
**Godot Version:**

3.2.2 Standard Version

**OS/device including Version:**

Mac OS 10.15.7

**Issue description:**

For a better coding experience I've set up GDScript with VisualStudio Code! This works perfectly fine besides one exception. If I create a new scene with Godot and attach a script and then give the script a class_name

For example:

class_name: Player

Visual Studio Code does not recognize the class name until I close Godot and reopen it.

**Steps to reproduce:**
See Issue description

**Comment by Shatur95** [comment] 2020-10-14 12:23
Duplicate of #225.

**Comment by Calinou** [comment] 2020-10-14 13:13
Duplicate of #225. Apologies for not finding the issue before closing https://github.com/godotengine/godot/issues/42786…

**Closed by Calinou** 2020-10-14 13:13 UTC
