### ISSUE TITLE
Extra pair of Quotation Marks on autocomplete

### ISSUE THREAD

**Issue by zMenta** [godotengine/godot-vscode-plugin#406] opened 2022-08-12 03:03 UTC
### Godot version

3.5 stable

### VS Code version

1.70.1

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

By selecting the auto-completion option **when you already wrote the ""** on functions that take strings, it will write an extra pair of quotation marks.

Code completion suggestion:
![image](https://user-images.githubusercontent.com/70714721/184276624-00fd2ac2-2776-4d73-abf2-79c2e9489341.png)

Output:
![image](https://user-images.githubusercontent.com/70714721/184276561-7524562b-c831-4610-b947-a35604badd25.png)

### Steps to reproduce

1. Write a function that takes a string, for example emit_signal(), connect(), is_action_pressed(), etc;
2. Type "" inside the function parenthesis;
3. Wait for the auto complete pop up appears;
4. Select an auto complete option.

**Comment by Calinou** [comment] 2022-08-12 11:46
Duplicate of https://github.com/godotengine/godot/issues/48436.

**Closed by Calinou** 2022-08-12 11:46 UTC
Labels: bug
