### ISSUE TITLE
Autocompleted functions and etc don't close the bracket, autocompletions for some strings break

### ISSUE THREAD

**Issue by endigma** [godotengine/godot-vscode-plugin#305] opened 2021-11-20 21:13 UTC
when tab completing functions, it goes `func(>` instead of `func(>)` with > being the cursor. 

writing `"` then tab completing a string does this sometimes

![image](https://user-images.githubusercontent.com/34945114/142741093-bcf986ac-59e7-4417-9127-dc974c91dd15.png)

**Comment by Calinou** [comment] 2021-11-20 21:46
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/142.

**Closed by Calinou** 2021-11-20 21:46 UTC
