### ISSUE TITLE
Rename symbol sometimes does not work properly

### ISSUE THREAD

**Issue by GianptDev** [godotengine/godot-vscode-plugin#448] opened 2023-01-31 14:59 UTC
### Godot version

3.5.stable

### VS Code version

1.74.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

Sometimes when I rename a variable, such as a constant or class name, anything that has a similar name but is not related to a variable get renamed too, renaming symbols does not take in account object properties and sometimes renaming will not work at all.

example:
```gdscript

class Thing extends Reference:
    var foo: bool = false; # Want to rename this to "different".

func bar () -> void:
    var new_thing: = Thing.new();
    var foo: bool = true; # this is renamed to "different".

    new_thing.foo = true; # This is untouched.

    for a in range(10): # renaming a to b does nothing.
        print(a);
```

### Steps to reproduce

right click -> rename symbol

I tried classes and loops, those seem to have more problems.

**Comment by atirut-w** [comment] 2023-02-01 02:13
This is a duplicate of #361, which should also have been closed since this issue is with Godot's LSP server. See https://github.com/godotengine/godot/issues/65563

**Closed** 2023-09-12 06:54 UTC
Labels: bug, language server
