### ISSUE TITLE
Code highlight stays at same color

### ISSUE THREAD

**Issue by EduardoJuliao** [godotengine/godot-vscode-plugin#558] opened 2023-12-27 21:37 UTC
### Godot version

4.1.1

### VS Code version

1.85.1

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

In some files the code highlight won't work and will stay at the same color:

VSCode (with github dark color scheme):
![image](https://github.com/godotengine/godot-vscode-plugin/assets/6979395/67aae296-9534-46f5-8bae-02df27ccfc8e)

VSCode (with GDScript color theme):
![image](https://github.com/godotengine/godot-vscode-plugin/assets/6979395/9003eb19-3fea-4d9e-b474-f7ea8c069789)

Godot: 
![image](https://github.com/godotengine/godot-vscode-plugin/assets/6979395/85528e95-0ffd-4ead-94d9-8024af1063e7)

### Steps to reproduce

Copying the code above will have the same issue in different files

``` GDScript
func _set_sprite(device_name:String) -> void:
    if device_name == InputHelper.DEVICE_XBOX_CONTROLLER:
        button_sprite.texture = button_sprites.button_sprites.xbox.interact;
    if device_name == InputHelper.DEVICE_PLAYSTATION_CONTROLLER:
        button_sprite.texture = button_sprites.button_sprites.ps.interact;
    if device_name == InputHelper.DEVICE_SWITCH_CONTROLLER:
        button_sprite.texture = button_sprites.button_sprites.switch.interact;
    if device_name == InputHelper.DEVICE_SWITCH_JOYCON_LEFT_CONTROLLER:
        button_sprite.texture = button_sprites.button_sprites.switch.interact;
    if device_name == InputHelper.DEVICE_SWITCH_JOYCON_RIGHT_CONTROLLER:
        button_sprite.texture = button_sprites.button_sprites.switch.interact;
    if device_name == InputHelper.DEVICE_KEYBOARD:
        button_sprite.texture = button_sprites.button_sprites.keyboard.interact;
```

**Comment by DaelonSuzuka** [comment] 2023-12-29 02:46
Yeah, that's a weird one. I tried your code with 1.3.1 and I see this:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/e46668ea-ad21-4daa-bccd-653ef1ebc1e1)

I have no idea what's causing this for you or why I can't replicate it. The syntax highlighting has been modified a lot since 1.3.1, and I strongly suspect that this will be fixed in the next version.

Here's what your code looks like to me using the latest build (from PR #559):

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/b060cd76-5a92-4fe7-ad41-3f33f9f7c192)

**Comment by EduardoJuliao** [comment] 2023-12-30 01:41
I'll wait for the next version and check if it fixes or not, but it's a very weird one.

I was trying to reproduce the code and I have this, the highlight partially works

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6979395/1ad87f69-656c-4900-8b29-1bf169de03bd)

Now, if I add `-> void:`, it breaks the highlight.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6979395/b16a3f83-2efb-4e8a-a90c-4013d796b161)

**Comment by DaelonSuzuka** [comment] 2024-02-28 04:23
@EduardoJuliao Are you still experiencing this issue since the release of `2.0.0`?

**Comment by Armand-Alvarez** [comment] 2024-07-27 01:23
I am experiencing the same issue. Syntax highlighting breaks if I add a return type after my function declaration.

**Comment by Armand-Alvarez** [comment] 2024-07-27 01:26
Similar to above, my syntax highlighting breaks when I have a returnt type included in my function declaration. See example below:
![image](https://github.com/user-attachments/assets/f209eb2e-b3fd-40d3-8628-923be5370d65)

And without the return type declared:
![image](https://github.com/user-attachments/assets/faea4f16-297c-4cb5-b173-cbc6c9f8ae73)

**Comment by Armand-Alvarez** [comment] 2024-07-27 20:00
Disregard. I disabled a separate gdscript extension and my syntax highlighting came back.

**Comment by DaelonSuzuka** [comment] 2024-07-27 22:19
This issue was originally for a previous version of the extension, and all the syntax highlighting has been significantly rewritten since then. Since the original author never confirmed that he's still experiencing this problem, I'm going to consider this resolved.

**Closed by DaelonSuzuka** 2024-07-27 22:19 UTC
Labels: bug

**Comment by Robert-K** [comment] 2024-08-01 18:56
Unfortunately I'm also experiencing this issue.
No gdextensions, latest VSCode, latest godot-tools, Godot 4.2+
![image](https://github.com/user-attachments/assets/54393520-af38-4566-b30a-e2a406a9057b)

**Comment by DaelonSuzuka** [comment] 2024-08-01 19:03
@Robert-K Do you mind pasting that code/file into a code box so I can try and reproduce the problem?

**Comment by Robert-K** [comment] 2024-08-01 19:59
Sure:

```
@tool
extends Node

# Get the bounds ([min, max]) of the polygon
func get_bounds(polygon: PackedVector2Array) -> Bounds2:
	var min_point := Vector2.INF
	var max_point := -Vector2.INF
	for point in polygon:
		min_point = Vector2(min(min_point.x, point.x), min(min_point.y, point.y))
		max_point = Vector2(max(max_point.x, point.x), max(max_point.y, point.y))
	return Bounds2.new(min_point, max_point)

# Make the polygon's centroid the origin
# Modifies the original
func center_polygon(polygon: PackedVector2Array):
	var bounds := get_bounds(polygon)
	var center := (bounds.min + bounds.max) / 2
	for i in range(polygon.size()):
		polygon[i] -= center
```

It happens on any function with a return type for me. Note that -> uses a ligature with my font (Jetbrains Nerdfont)

**Comment by DaelonSuzuka** [comment] 2024-08-01 20:01
> ligature

I'm gonna completely loose my mind if ligatures have somehow been causing these intermittent highlighting problems for years.

**Comment by mn113** [comment] 2024-11-08 13:41
I also had this issue; everything in the function body after the return type was being coloured uniformly.

Figured out it was caused by having both `godot-tools` (by Geequlim) and `gdscript` (by jjkim) VSCode extensions installed.

Syntax highlighting in `.gd` files returned to normal after uninstalling jjkim's extension.

**Comment by DaelonSuzuka** [comment] 2024-11-08 16:53
@mn113 Thanks for the report. I'm considering adding a check at startup to look for potentially conflicting extensions and display a popup to the user...

**Comment by Robert-K** [comment] 2024-11-10 16:00
@mn113 That fixed it for me :)) Thanks so much!
