### ISSUE TITLE
Smart Prompt Code press Tab or Enter to select the code after the extra double quotes and reverse brackets will appear

### ISSUE THREAD

**Issue by Yakumo-Yukari** [godotengine/godot-vscode-plugin#352] opened 2022-04-24 09:42 UTC
### Godot version

3.4.4

### VS Code version

1.66.2

### Godot Tools VS Code extension version

1.2.0

### System information

Windows 10

### Issue description

![bug](https://user-images.githubusercontent.com/12076232/164970276-57ce4eb0-05d8-44bc-bdb0-1663aa52a914.gif)

Smart Prompt Code press Tab or Enter to select the code after the extra double quotes and reverse brackets will appear

The code will become `if Input.is_action_pressed(""ui_up"("`

### Steps to reproduce

![bug](https://user-images.githubusercontent.com/12076232/164970276-57ce4eb0-05d8-44bc-bdb0-1663aa52a914.gif)

**Comment by Calinou** [comment] 2022-04-24 14:57
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/142

**Closed by Calinou** 2022-04-24 14:57 UTC
Labels: bug
