### ISSUE TITLE
Moving a file doesn't update editor

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-vscode-plugin#185] opened 2020-06-02 22:34 UTC
When I move a file from `A/B/C.gd -> AA/BB/C.gd`, the editor doesn't refactor the file change.

For example, assume I have a `Scripts` folder and in that folder are all my scripts. Let's say I want to restructure that folder by adding folders to group different types of scripts:

So for example if I have this:

```
- Scripts
-- ButtonA.gd
-- ButtonC.gd
-- ButtonD.gd
-- EnemyA.gd
-- EnemyB.gd
```

I would like to then change it to this:
```
- Scripts
-- Enemy
--- EnemyA.gd
--- EnemyB.gd
-- UI
--- ButtonA.gd
--- ButtonC.gd
--- ButtonD.gd
```

The editor however, doesn't update nodes with that script attached to it. To do so you currently have to organize the files within the editor instead in order for the refactoring to take place.

**Comment by Calinou** [comment] 2020-06-03 07:24
The editor uses its own file moving logic, which isn't usable from outside. I don't know if this can be implemented on the LSP side of things.

**Comment by DaelonSuzuka** [comment] 2024-02-28 06:20
Duplicate of #33

**Closed by DaelonSuzuka** 2024-02-28 06:20 UTC
Labels: enhancement
