### ISSUE TITLE
godot 4.0stable debugger not working

### ISSUE THREAD

**Issue by rkxhs02** [godotengine/godot-vscode-plugin#460] opened 2023-03-19 11:20 UTC
### Godot version

godot 4.0 stable

### VS Code version

1.762

### Godot Tools VS Code extension version

Latest

### System information

window10

### Issue description

godot 4.0stable debugger not working

### Steps to reproduce

The following error occurs when running gdscript godot debug run.

Failed to launch Godot instance: Error: Command failed: "D:\download\Godot_v4.0-stable_win64.exe" --path "D:\TestGame" --remote-debug 127.0.0.1:6006 '"D:\download\Godot_v4.0-stable_win64.exe"'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ� ��ġ ������ �ƴմϴ�.

Godot_v3.5.2-Stable works well.

Isn't 4.0 not yet supported?

**Comment by DaelonSuzuka** [comment] 2023-03-19 14:12
It's not supported yet.

**Comment by atirut-w** [comment] 2023-03-20 01:12
Isn't this a duplicate?

**Comment by DaelonSuzuka** [comment] 2023-03-20 02:08
There's going to be a lot of duplicates of this issue until the feature is done.

**Comment by atirut-w** [comment] 2023-03-20 05:13
Someone ought to pin the original issue then. Should help with the dupes to some degree.

**Comment by DaelonSuzuka** [comment] 2023-03-20 19:23
> Well 3.5.2 doesn't work either. Debugger do stop on debug points but doesn't let expect/edit any variables, and stepping/resuming just hangs the process until restarted.

As far as I'm aware, that behavior has always been inconsistent at best. Given the complexity of the system, the limited amount of time I can devote to this project, and the fact that I don't really use debuggers, personally.... Getting it working perfectly has not been a very high priority for me.

**Comment by microBob** [comment] 2023-03-21 07:08
This may have already been discussed in another issue, but the "error" that it is failing on is that the launch command is formatted incorrectly. 

```bash
Invalid debug host address, it should be of the form <protocol>://<host/IP>:<port>
```

The extension is only sending `<IP>:<port>` and is missing `<protocol>://`

You can kinda get around this by setting the `address:` property in `launch.json` to `http://<IP>` (i.e. `http://127.0.0.1`). It'll launch correctly, although the extension will interpret the info message from Vulkan as an error (I think it's just logging info).

**Comment by moonraymurray** [comment] 2023-03-25 00:21
I was able to get it to run by putting ws:// infront of 127.0.0.1 - ws://127.0.0.1
I still get issues when it comes to trying to pause from the debugger in VS code and also step through not working.
I am unsure as to how to hook in Debug Adapter server aswell.

**Comment by JoeTortuga** [comment] 2023-03-29 22:55
> 

This worked for me, but it ignores all the debug stops.  I checked the debug was passing the right parameters per the Godot spec, it's just not actually respecting it.

**Comment by newjbl** [comment] 2023-04-02 04:32
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "GDScript Godot",
            "type": "godot",
            "request": "launch",
            "project": "F:/Godot/GodotPro/test_vscode",
            "port": 6005,
            "address": "127.0.0.1",
            "launch_game_instance": true,
            "launch_scene": false,
            "debugServer": 6006,

        }
    ]
}


add "debugServer":6006, it can be start the godot project by F5. but it ignores all the debug stops....

**Comment by akien-mga** [comment] 2023-04-05 10:40
Duplicate of #389

**Closed by akien-mga** 2023-04-05 10:40 UTC
Labels: bug
