### ISSUE TITLE
Auto-complete issue

### ISSUE THREAD

**Issue by YangTegap** [godotengine/godot-vscode-plugin#281] opened 2021-06-22 19:05 UTC
As seen below, I am attempting to autofill `"ui_left"` in the function `Input.is_action_pressed()` However, it autocompletes as `Input.is_action_pressed(""ui_left"("` instead.
![autocomplete_issue](https://user-images.githubusercontent.com/68930804/122984590-69c57e00-d35a-11eb-8d3a-160ac42de1dd.gif)

**Comment by Calinou** [comment] 2021-06-22 19:24
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/184.

**Closed by Calinou** 2021-06-22 19:24 UTC
