### ISSUE TITLE
Couldn't connect to the GDScript language server.

### ISSUE THREAD

**Issue by rodrigofbm** [godotengine/godot-vscode-plugin#154] opened 2020-03-01 18:50 UTC
I'm facing this issue with Godot 3.2 on Manjaro, VS code 1.42.0

```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=19.0.1
DISTRIB_CODENAME=Kyria
DISTRIB_DESCRIPTION="Manjaro Linux"
```

**Comment by aaronfranke** [comment] 2020-03-03 07:23
What happens if you click the reconnect button?

Do you have multiple instances of Godot open? That messes up the plugin.

**Comment by rodrigofbm** [comment] 2020-03-03 20:37
@aaronfranke the error come back when I click retry.
Only one Godot open

**Comment by Bromeon** [comment] 2020-04-12 21:00
I can reproduce this problem with newer Godot 3.2 versions from commit https://github.com/godotengine/godot/commit/24b27043fec7ef9a4baf2c5ecab67fc20563b586 onwards. I did a git bisect, earlier Godot versions (including official 3.2 release) are working for me.

The reason is most likely that the language server in Godot was rewritten from Websockets to raw TCP, in pull request https://github.com/godotengine/godot/pull/35864. I assume the VS Code client would need to be adjusted accordingly.

**Comment by rafaeldelboni** [comment] 2020-04-13 00:40
I think this branch need to be merged as well to work with the recent versions of godot
https://github.com/godotengine/godot-vscode-plugin/pull/141

**Closed** 2020-05-13 15:12 UTC
Labels: bug

**Comment by FabienSailliet** [comment] 2020-09-12 11:35
If this can help anyone, I had this issue with the Godot version provided in the Ubuntu repositories (`3.2.stable.custom_build`, indicated in apt as `3.2-stable-2`), downloading the engine from the website fixed it (version `3.2.2.stable.official`).

**Comment by Calinou** [comment] 2020-09-12 11:54
@FabienSailliet The Godot version in the Ubuntu repositories is 3.2 (not 3.2.2). Its GDScript language server only supports WebSockets, not TCP.

**Comment by FabienSailliet** [comment] 2020-09-12 12:05
Ok, but it is strange as it didn't work even when I switched to WebSockets in VSCode settings.

Thanks for the information.

**Comment by thejacer87** [comment] 2020-09-20 00:28
> @FabienSailliet The Godot version in the Ubuntu repositories is 3.2 (= 3.2.0, it's not 3.2.2). Its GDScript language server only supports WebSockets, not TCP.
> 
> Linux distribution repositories are generally frozen, which means their packages don't receive updates (except for security updates which are manually backported). As an alternative, use the official binary, use the [Flatpak](https://flathub.org/apps/details/org.godotengine.Godot), or build from source.

so if i use apt, the gdscript server won't connect. if i use the flatpak, it won't launch vscode

same settings: 
![image](https://user-images.githubusercontent.com/6412919/93691672-5fa9e280-fa9d-11ea-91fa-bbe038bddb16.png)

and i can manually run  `$ code ~/project_dir --goto Scripts/State.gd:3` and it launched vscode just fine

not sure what to do from here

**Comment by capnm** [comment] 2020-09-20 02:13
> not sure what to do from here

`$ which code` shows you the code path ...

**Comment by Calinou** [comment] 2020-09-20 12:14
> if i use the flatpak, it won't launch vscode

This is due to sandboxing limitations. See a workaround here: https://github.com/flathub/org.godotengine.Godot

**Comment by lockious** [comment] 2022-02-11 15:04
Bruh 4.0 on Arch linux this happen again

**Comment by Richard74Huang** [comment] 2022-04-28 06:17
4.0 alpha 6 on macOS has this issue too.

**Comment by Calinou** [comment] 2022-04-28 14:02
> 4.0 alpha 6 on macOS has this issue too.

The language server likely has had incompatible changes not taken into account by this extension yet.

cc @Razoric480

**Comment by oEjk** [comment] 2022-04-30 00:20
arch (artix) godot v3.4.4.stable.arch_linux
is bug

**Comment by LimePotato** [comment] 2023-09-05 08:32
(Arch Linux) I've noticed if installed via Steam it wont connect, but if installed via the repos it does work.

I'll just use the arch repo version from here out.
