### ISSUE TITLE
Outline Symbols Missing in Various Scenarios with class_name and extends Placement in GDScript

### ISSUE THREAD

**Issue by SirManfred** [godotengine/godot-vscode-plugin#744] opened 2024-10-27 12:24 UTC
### Godot version

4.3 stable

### VS Code version

1.94.2

### Godot Tools VS Code extension version

2.3.0

### System information

Windows 10 Pro

### Issue description

In VSCode with the Godot extension, symbols in the Outline panel only display under specific conditions involving the placement of `extends` and `class_name` declarations in GDScript files.

**Instances When Symbols Work:**

- `extends` is on the first line, with or without `class_name` in the script.
- `extends` is on the first line and `class_name` on the second line.
- `extends` is on the second line, with `class_name` on the third line.
- `class_name` is on the second line, with `extends` on the third line.
- A comment is on the first line, followed by `class_name` on the second line and `extends` on the third line.

**Instances When Symbols Don’t Work:**

- The first line is empty, and `extends` is on any other line (without `class_name` in the script).
- A comment is on the first line, and `extends` is on any other line (without `class_name` in the script).
- `class_name` is on the first line, and `extends` is on any other line.

In summary, symbols only appear if `extends` is on the first line in scripts without `class_name`. If `class_name` is present, `extends` can appear on any line, but symbols fail to display if `class_name` is the first line and `extends` appears afterward.

**Expected Behavior:**
Symbols should populate in the Outline regardless of the line position of `class_name` and `extends` declarations, allowing flexibility in script structure, such as placing comments or leaving the first line empty, without affecting the Outline's functionality.

### Steps to reproduce

See the attached script files and try out the different scenarios listed in the description

```gdscript
extends Node
class_name SomeClass

var variable1: int = 1
var variable2: String = "Hello"
var variable3: bool = true

func _ready() -> void:
	print(variable1)
	print(variable2)
	print(variable3)

func _process(delta: float) -> void:
	if(variable3):
		print("Processing..." + str(delta))
		variable3 = false
		print("Done")
```

**Comment by DaelonSuzuka** [comment] 2024-10-27 14:07
Duplicate of #658

**Closed by DaelonSuzuka** 2024-10-27 14:07 UTC
Labels: bug
