### ISSUE TITLE
Unexpected indentation when moving lines

### ISSUE THREAD

**Issue by froggestspirit** [godotengine/godot-vscode-plugin#399] opened 2022-07-24 18:18 UTC
### Godot version

3.5 RC7

### VS Code version

1.58.2

### Godot Tools VS Code extension version

1.3.1

### System information

Ubuntu 21.10

### Issue description

When using ALT + Up/Down to move a line of code, indentation does not work as intended. The way it currently works mirrors the behaviour of this bug
https://github.com/microsoft/vscode-python/issues/6886

### Steps to reproduce

From  https://github.com/microsoft/vscode-python/issues/6886, select the line "move_to_end", then keep pressing ALT+Down to move it to the end
```

move_to_end


class Foo:
    def __init__(self):
        pass

    def bar(self):
        pass


class Baz:
    pass
```

**Comment by Calinou** [comment] 2022-07-24 19:02
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/130.

**Closed by Calinou** 2022-07-24 19:02 UTC
Labels: bug
