### ISSUE TITLE
autocomplete adds extra characters

### ISSUE THREAD

**Issue by Tobio89** [godotengine/godot-vscode-plugin#470] opened 2023-04-29 09:37 UTC
### Godot version

v3.4.4.stable.official [419e713a2]

### VS Code version

1.77.3

### Godot Tools VS Code extension version

1.3.1

### System information

MacOS Ventura 13.3.1

### Issue description

When I use autocomplete on strings such as `ui_accept`, if I accept the autocomplete, it prints extra quote and parenthesis characters that break the string, and I have to go back and fix it.

Example:
`if Input.is_action_just_pressed(""ui_accept"("`

![image](https://user-images.githubusercontent.com/44494591/235295846-9f5c445f-daf1-40e7-9a13-c29cea3f763a.png)

This is the only issue I've run into so far, really grateful for this plugin, this is the only thing that I've found that significantly affects me whilst using GDScript in VSCode.

### Steps to reproduce

type `if Input.is_action_just_pressed("` and then press enter or tab to accept the autocomplete.

**Comment by DaelonSuzuka** [comment] 2023-04-29 13:06
This is a known issue, and unfortunately it's not actually related to this extension. All the autocomplete suggestions are provided by the Language Server which is a component of the Godot editor. You should open an issue over on the [Godot repo](https://github.com/godotengine/godot/issues).

**Comment by Tobio89** [comment] 2023-05-01 04:24
Thanks, I'll do that :)

**Comment by Tobio89** [comment] 2023-05-01 05:04
https://github.com/godotengine/godot/issues/76639

I made the issue, I thought I'd share it here too in case other people stumble upon it.
Shall I close this issue?

**Comment by Calinou** [comment] 2023-05-01 21:41
- Duplicate of https://github.com/godotengine/godot/issues/48436.

**Closed by Calinou** 2023-05-01 21:41 UTC
Labels: bug, language server
