### ISSUE TITLE
Enabling type hints in editor adds extra bracket

### ISSUE THREAD

**Issue by boruok** [godotengine/godot-vscode-plugin#323] opened 2022-02-24 15:43 UTC
**Issue description**
```gdscript
func _set(property: String, value) -> bool:(  # sadface

func _set(property: String, value) -> bool:   # expected
```
**Steps to reproduce**
1. enable add type hints in editor -> text editor -> completion -> add type hints
2. try to type node method

**Comment by Calinou** [comment] 2022-02-24 16:28
@boruok Which Godot version and VS Code extension versions are you using?

**Comment by raulsntos** [comment] 2022-02-24 17:12
I can confirm with:
- Godot v3.4.2.stable.mono.official [`45eaa2daf`](https://github.com/godotengine/godot/commit/45eaa2daf)
- VS Code extension compiled as of commit 12858a2e0525d22b20a7c8760dc752ede0eaf44f

The issue seems to originate on Godot itself, since the extension receives this message from the LSP server:

```json
{
	"id": 112,
	"jsonrpc": "2.0",
	"result": {
		"command": {
			"command": "",
			"title": ""
		},
		"data": {
			"context": null,
			"position": {
				"character": 6,
				"line": 12
			},
			"textDocument": {
				"uri": "file:///media/raulsntos/Data/GodotProjects/vscode-test/Main.gd"
			}
		},
		"deprecated": false,
		"detail": "",
		"documentation": {
			"kind": "markdown",
			"value": "\tfunc Object._set(property: String, value: Variant) -> bool\n\nVirtual method which can be overridden to customize the return value of `set`.\n\nSets a property. Returns `true` if the `property` exists.\n\n"
		},
		"filterText": "",
		"insertText": "_set(property: String, value) -> bool:(",
		"kind": 2,
		"label": "_set(property: String, value) -> bool:",
		"preselect": false,
		"sortText": ""
	}
}
```

Notice the property `insertText` that already includes the closing parenthesis.

The code responsible is: https://github.com/godotengine/godot/blob/4dc8214831d1617e7f5f06e8294fb37ea23dae59/modules/gdscript/language_server/gdscript_text_document.cpp#L287-L291 (affects both `master` and `3.x`).

Godot adds the closing parenthesis when the label doesn't end with `):`, this works when not using type hints since the label would be:

```gdscript
_set(property, value):
```

But doesn't work when using type hints since the label no longer ends with `):`:

```gdscript
_set(property: String, value) -> bool:
```

**Comment by boruok** [comment] 2022-02-25 00:16
@Calinou 
godot-tools v1.1.3
v3.4.3.rc2.official [0ea54d07f]

**Closed** 2022-06-15 13:31 UTC
Labels: bug, confirmed
