### ISSUE TITLE
Log not updating in real time

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#368] opened 2022-05-20 11:32 UTC
### Godot version

v3.4.4.stable.official [419e713a2]

### VS Code version

1.67.2

### Godot Tools VS Code extension version

1.3.0

### System information

N/A

### Issue description

When launching a game from VSCode, the log does not seem to update in real time even if you log print something every frame.

### Steps to reproduce

1. New node
2. New script inheriting it
3. Put in this function:
```gdscript
func _physics_process(delta: float) -> void:
    print("a")
```
4. Launch project from VSCode
5. Log does not update in real time.

**Comment by ZachIsAGardner** [comment] 2022-06-16 15:06
I believe we've had the same problem https://github.com/godotengine/godot-vscode-plugin/issues/382

**Comment by Calinou** [comment] 2022-06-16 15:13
Duplicate of #382.

**Closed by Calinou** 2022-06-16 15:13 UTC
Labels: bug

**Comment by atirut-w** [comment] 2022-06-17 11:48
Hold on, this issue is older than #382 though?
