### ISSUE TITLE
In some cases tool tip with the type of the variable doesn't show up

### ISSUE THREAD

**Issue by nanoblit** [godotengine/godot-vscode-plugin#207] opened 2020-06-27 06:37 UTC
In the example shown below, when I hover over child_position variable I expect it to show me a tool tip with the type Vector2, but it doesn't.

![Untitled](https://user-images.githubusercontent.com/7485739/85916376-9a123380-b850-11ea-8590-4227d4c29335.png)

**Comment by Calinou** [comment] 2020-06-27 17:25
I don't think type inference information is exposed by the LSP server, or is it?

**Comment by linkpy** [comment] 2020-10-28 14:35
The issue is from the LSP server as the "hover" request is sent and the server replies with an empty result.

Hovering `child` shows a tool tip, but it doesn't seem to work with some local variables (inside functions). 
Opened https://github.com/godotengine/godot/issues/43164 to fix that bug on the server side.

**Comment by akien-mga** [comment] 2021-03-25 14:57
Fixed by https://github.com/godotengine/godot/pull/47338.

**Closed by akien-mga** 2021-03-25 14:57 UTC
Labels: enhancement, language server
