### ISSUE TITLE
Unable to ctrl-click to view documentation

### ISSUE THREAD

**Issue by nmearl** [godotengine/godot-vscode-plugin#81] opened 2018-09-04 00:14 UTC
Linking to documentation via control-clicking class names raises the error

```Unable to open 'vscode.previewHtml': resource is not available.```

VSCode: 1.26.1
Godot: v3.0.6stable

**Comment by Knuds1** [comment] 2019-07-31 12:55
Duplicate of #100

**Comment by Geequlim** [comment] 2019-10-10 05:27
The native documentation is now implemented with custom specifications. Documentations are send from the server realtime and renderer as in a spatial webview in VSCode. 

I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)

**Closed by Geequlim** 2019-10-10 05:27 UTC
