### ISSUE TITLE
GDScript (files *.gd) starting with a comment and no class_name, Outline not working

### ISSUE THREAD

**Issue by BrianOSH** [godotengine/godot-vscode-plugin#760] opened 2024-12-01 11:52 UTC
### Godot version

4.3

### VS Code version

1.95.3

### Godot Tools VS Code extension version

2.3.0

### System information

Linux Mint

### Issue description

Godot's default language GDScript (files *.gd) starting with a comment and no class_name, Outline reports "no symbols found in document"

### Steps to reproduce

Godot's default language GDScript (files *.gd) starting with a comment and no class_name, Outline reports "no symbols found in document"

Create a file (test.gd) copy code lines to file.
outline reports "no symbols found in document"

Change line "extends Node" to "class_name test extends Node" or remove comments at start of file.
symbols now appear in outline.

```
#───────────────
# (C) 2024
#───────────────
extends Node

func F1():
	pass

func F2():
	pass

func F3():
	pass

```

**Comment by DaelonSuzuka** [comment] 2024-12-02 13:50
Duplicate of #658, fixed in https://github.com/godotengine/godot/pull/99295, merged into Godot 5 days ago.

**Closed by DaelonSuzuka** 2024-12-02 13:50 UTC
Labels: bug
