### ISSUE TITLE
Godot game freezes after stepping or continuing from first breakpoint

### ISSUE THREAD

**Issue by shrnjad** [godotengine/godot-vscode-plugin#175] opened 2020-05-09 13:04 UTC
I setup the plugin fine like described in the readme. Everything is connected and I start the game with F5.

The debuger breaks at a breakpoint. Local variables, stack trace, etc. is all displayed correctly.

However, when I step or continue from here, the game just freezes. Without setting a breakpoint it does not freeze but runs fine.

I am using GDScript without mono.
Godot editor version is 3.2.1

How can I fix the issue?

**Comment by Razoric480** [comment] 2020-05-09 14:52
I'm unable to replicate the bug on this end.

What OS are you using?
Does it happen with all lines of code or does it fail in a particular function for some reason?
Does it happen with all of your projects? I.E. if you make a brand new project with some throwaway lines and try to debug it, does it happen there too?

**Comment by Mootook** [comment] 2020-05-09 21:13
I was experiencing this issue earlier today when loading an old project. Some unused and forgotten scripts had syntactical errors and references to class properties that no longer existed. The Debug Console hints at it on the first launch, and after removing those files, everything worked as expected.

**Comment by GGalizzi** [comment] 2020-05-23 20:50
This kind of sounds like the same issue I'm encountering, although in my case it just freezes as soon as the game starts. Debugging works for a few minutes when I first launch Godot, but after some time when I start I run debug on vscode the game freezes on load, if there is no breakpoint then it doesn't happen. I have to restart de Godot editor for debugging to start working again, but I have to do that every 10 or 15 minutes which is super irritating.

**Comment by Razoric480** [comment] 2020-05-23 20:52
I've managed to confirm that last one, and will investigate and see about issuing a fix once I have the time for it. With any luck it will also fix the former bug(s) as well.

**Comment by Razoric480** [comment] 2020-05-24 15:18
I've identified an issue that the server was not being closed properly, particularly when the godot process was killed by the user instead of through the debugger 'stop' command.

I've added a PR; could anyone who had this bug here see if it still happens if they try to check it out and compile? I'm posting the vsix in a zip here if you'd rather not go through the hassle of installing NPM/TSC and compiling.

[godot-tools-server-fix.zip](https://github.com/godotengine/godot-vscode-plugin/files/4673792/godot-tools-server-fix.zip)

**Comment by Havok06** [comment] 2020-05-26 08:29
Hello, I'm having the same kind of issue. After 1.1.0 version of the extension was released I managed to debug in VSCode for maybe two days and now I can't use it anymore.

It breaks at the breakpoint but then I can't step in or even continue. I also don't get variables info or callstack. On the other hand, I do get the scene tree.
I tried installing the VSIX you mentionned but then it wasn't even breaking (maybe I did something wrong ?). Is there a way to close the server properly as a temporary fix? I will know not to close the game manually and always stop it through VSCode in the future.

thanks for the great work :)

**Comment by Geequlim** [comment] 2020-05-26 13:16
@Havok06  Did you started a thread in your GDScript code ?

**Comment by Razoric480** [comment] 2020-05-26 14:14
@Havok06 Closing and re-opening VSCode will shutdown everything. I'm unable to replicate the issue, however, especially with the fixed extension I posted.

**Comment by Havok06** [comment] 2020-05-27 20:07
@Geequlim I have not used threads.

@Razoric I have tried closing and opening VSCode, the issue persists. I have tried on an empty project, all seems to work even after I closed the app randomly.
So I guess the issue is in my project.

**Comment by Razoric480** [comment] 2020-05-28 17:33
I'd be curious if you can narrow it down to what, particular, you are doing that causes the issue in your project. It should be something that should get caught by the VSCode debugger, as it'd be symptomatic of a deeper issue.

**Comment by conrev** [comment] 2020-06-08 03:26
> I've identified an issue that the server was not being closed properly, particularly when the godot process was killed by the user instead of through the debugger 'stop' command. As a result, the VSCode debugger was _receiving_ debug messages, but it couldn't send any - so it stopped when hitting a breakpoint as it got the debug_enter notification, but then failed to get the stack dump it needs to actually indicate where and how.
> 
> I've added a PR, #183 ; could anyone who had this bug here see if it still happens if they try to check it out and compile? I'm posting the vsix in a zip here if you'd rather not go through the hassle of installing NPM/TSC and compiling.
> 
> [godot-tools-server-fix.zip](https://github.com/godotengine/godot-vscode-plugin/files/4673792/godot-tools-server-fix.zip)

I've tested this and it seems like the debugger can break more consistently and i dont have to restart vscode from time to time. Also, It seems that now the i can see godot's output from vscode (print statement and such, dont know if this is intended). However i started having another issue with vscode saying it cannot connect to language server ( thus losing all the language features ) and the engine started spitting errors like
 `ERROR: _parse_request: Not enough response headers, got: 1, expected >= 4.
   At: modules/websocket/wsl_server.cpp:49.`

Maybe i did something wrong, totally new to this extension.

**Comment by Razoric480** [comment] 2020-06-08 03:31
I compiled the VSIX from the latest master, so fixes that weren't there before now are. Including output now working.

> However i started having another issue with vscode saying it cannot connect to language server ( thus losing all the language features ) and the engine started spitting errors like
so you may have to go into godot-tools' settings and make sure that the language server is set to connect to WS (as the TCP implementation is going to be in Godot 3.2 and isn't out yet.)

**Comment by RobTheFiveNine** [comment] 2020-06-08 14:25
> I've identified an issue that the server was not being closed properly, particularly when the godot process was killed by the user instead of through the debugger 'stop' command. As a result, the VSCode debugger was _receiving_ debug messages, but it couldn't send any - so it stopped when hitting a breakpoint as it got the debug_enter notification, but then failed to get the stack dump it needs to actually indicate where and how.
> 
> I've added a PR, #183 ; could anyone who had this bug here see if it still happens if they try to check it out and compile? I'm posting the vsix in a zip here if you'd rather not go through the hassle of installing NPM/TSC and compiling.
> 
> [godot-tools-server-fix.zip](https://github.com/godotengine/godot-vscode-plugin/files/4673792/godot-tools-server-fix.zip)

I haven't tested the fix, but just checking in to confirm I have also been experiencing this and your conclusion of what was causing it was correct. If I stop my game using the stop button in vscode, then I can launch it again successfully, but closing it by clicking the close button on the game window that is launched will prevent being able to debug again until vscode is closed and relaunched.

In my case, I had a breakpoint set, and when I'd try to debug after closing the game window via the close button of the window, it'd reach the breakpoint and then stall the game execution there, but with no indicator in vscode that the breakpoint had been reached (thus no ability to continue execution etc.)

**Closed** 2020-09-08 13:56 UTC
Labels: bug

**Comment by EduardoCopat** [comment] 2021-03-14 02:29
Still happens intermittently to me.
