### ISSUE TITLE
Incorrect auto-completion with static typing enabled

### ISSUE THREAD

**Issue by Exerionius** [godotengine/godot-vscode-plugin#374] opened 2022-06-02 15:34 UTC
### Godot version

v3.4.4.stable.official [419e713a2]

### VS Code version

1.67.2

### Godot Tools VS Code extension version

1.2.0 (1.3.0 is broken, but it behaves the same)

### System information

Windows 10

### Issue description

Some of the auto-completion functionality works incorrectly when static typing is enabled in Godot.

Example 1.  
Built-in function auto-completion:
![FunctionAutoComplete](https://user-images.githubusercontent.com/13285909/171664533-5ac06f93-45b8-4c23-a5a5-d44e7617dd20.gif)
Inserts extra braces after function return type.

Example 2.  
Input map auto-completion:
![InputAutoComplete](https://user-images.githubusercontent.com/13285909/171664696-5fa0acf4-52d6-4284-9730-723896717c9a.gif)
Inserts extra quotes and an opening brace

### Steps to reproduce

Example 1.  
1. Enable type hints in Godot:
![image](https://user-images.githubusercontent.com/13285909/171665426-42eb6c97-9bd2-4529-92ef-5e14087bb1a1.png)
2. In VS Code type `func _re` and press Enter

Example 2.
1. Enable type hints in Godot (see Example 1 step 1)
2. In VS Code type `Input.is_action_just_pressed(` and press Enter

**Comment by Calinou** [comment] 2022-06-02 15:44
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/323 and https://github.com/godotengine/godot-vscode-plugin/issues/142

**Closed by Calinou** 2022-06-02 15:44 UTC
Labels: bug
